<?xml version="1.0"?>
<robot name="agv" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Base dimensions (meter) -->
  <xacro:property name="base_length" value="0.40"/>
  <xacro:property name="base_width"  value="0.30"/>
  <xacro:property name="base_height" value="0.12"/>

  <material name="grey"><color rgba="0.6 0.6 0.6 1"/></material>
  <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
  <material name="blue"><color rgba="0.2 0.2 0.8 1"/></material>

  <!-- base_footprint (root, no inertia) -->
  <link name="base_footprint"/>

  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- base_link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="5.0"/>
      <inertia ixx="0.10" ixy="0.0" ixz="0.0" iyy="0.10" iyz="0.0" izz="0.10"/>
    </inertial>
  </link>

  <!-- LiDAR frame -->
  <link name="laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="base_to_laser" type="fixed">
    <parent link="base_link"/>
    <child link="laser"/>
    <origin xyz="0.18 0.0 0.11" rpy="0 0 0"/>
  </joint>

  <!-- IMU frame -->
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 0.01"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="base_to_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0.0 0.10" rpy="0 0 0"/>
  </joint>

</robot>
